package com.antispam.blocker.domain.scoring

data class CallFeatures(
    val isContact: Boolean = false,
    val isRussianNumber: Boolean = false,
    val isForeignNumber: Boolean = false,
    val isShortCode: Boolean = false,
    val isStandardLen: Boolean = false,
    val isTollFree8800: Boolean = false,
    val isGeographical: Boolean = false,
    val isMobileRu: Boolean = false,
    val isValidRuRange: Boolean = false,
    val spoofingPrefixFlag: Boolean = false,
    val digitEntropy: Float = 0f,
    val repeatDigitRatio: Float = 0f,
    val maxSameDigitRun: Float = 0f,
    val beautifulNumberFlag: Boolean = false,
    val prefixRisk: Float = 0f,
    val callFrequency: Float = 0f,
    val isNightTime: Boolean = false,
    val recentBankApp: Boolean = false,
    val recentGovApp: Boolean = false,
    val recentMarketplaceApp: Boolean = false,
    val recentMessengerApp: Boolean = false,
    val previouslyRejected: Boolean = false,
    val inBlacklist: Boolean = false,
    val inAllowlist: Boolean = false,
    val hiddenNumber: Boolean = false,
    val callerVerifyFailed: Boolean = false,
    val userVulnerability: Float = 0f,
    val userBusinessActivity: Float = 0f,
    val contactsAvailable: Boolean = false,
    val usageAccessAvailable: Boolean = false,
    val reputationScore: Float = 0f,
    val sourceConfidence: Float = 0f
) {
    fun toFloatArray(): FloatArray = floatArrayOf(
        if (isContact) 1f else 0f,
        if (isRussianNumber) 1f else 0f,
        if (isForeignNumber) 1f else 0f,
        if (isShortCode) 1f else 0f,
        if (isStandardLen) 1f else 0f,
        if (isTollFree8800) 1f else 0f,
        if (isGeographical) 1f else 0f,
        if (isMobileRu) 1f else 0f,
        if (isValidRuRange) 1f else 0f,
        if (spoofingPrefixFlag) 1f else 0f,
        digitEntropy,
        repeatDigitRatio,
        maxSameDigitRun,
        if (beautifulNumberFlag) 1f else 0f,
        prefixRisk,
        callFrequency,
        if (isNightTime) 1f else 0f,
        if (recentBankApp) 1f else 0f,
        if (recentGovApp) 1f else 0f,
        if (recentMarketplaceApp) 1f else 0f,
        if (recentMessengerApp) 1f else 0f,
        if (previouslyRejected) 1f else 0f,
        if (inBlacklist) 1f else 0f,
        if (inAllowlist) 1f else 0f,
        if (hiddenNumber) 1f else 0f,
        if (callerVerifyFailed) 1f else 0f,
        userVulnerability,
        userBusinessActivity,
        if (contactsAvailable) 1f else 0f,
        if (usageAccessAvailable) 1f else 0f,
        reputationScore,
        sourceConfidence
    )

    companion object {
        const val FEATURE_COUNT = 32
    }
}
